version: "2"

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "3000:80"

  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
